### ISSUE TITLE
What was the workflow for this site?

### ISSUE THREAD

**Issue by laken** [joshkoenig/hillaryclintonisa_____butimvotingforheranyway.com#8]
Wondering what your workflow is to get the .md files in this repo published on the WP site. Thanks.

**Comment by joshkoenig** [comment]
I shamelessly copied the workflow from this project at work:

https://github.com/pantheon-systems/wordpress-at-scale/blob/master/CONTRIBUTING.md

It leverages this plugin:

https://wordpress.org/plugins/wp-github-sync/
